#
# Configuration
#
sudo: required
dist: trusty

language: node_js
node_js:
  - 11


before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

#
# Build Lifecycle:
#

before_install:
  - nvm install node
  - nvm use node 11

install: npm install


script:
  - git config user.name "$GH_USER"
  - git config user.email "$GH_MAIL"
#  - npm run build:prod:gh

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: $HEROKU_APP
  on:
    branch: master
